const data=window.PORTFOLIO, $=id=>document.getElementById(id);
$('name').textContent=data.name;$('about-text').textContent=data.about;
$('github').href=data.github;$('copyright').textContent=`© ${new Date().getFullYear()} · AI Portfolio`;
const labels={image:'图片',video:'视频',prompt:'Prompt'};
function el(tag,text,cls){const node=document.createElement(tag);if(text)node.textContent=text;if(cls)node.className=cls;return node}
function safeUrl(value){try{const url=new URL(value,location.href);return ['http:','https:'].includes(url.protocol)?url.href:''}catch{return ''}}
data.skills.forEach(s=>$('skills').append(el('span',s)));
if(!data.experience.length)$('experience').append(el('p','履历待补充。','notice'));
data.experience.forEach(x=>{const row=el('div',null,'resume-row');row.append(el('p',x.period));const body=el('div');body.append(el('h3',x.title),el('p',x.description));row.append(body);$('experience').append(row)});
let opener;
function show(work,button){opener=button;const body=$('detail-content');body.replaceChildren();body.append(el('h2',work.title),el('p',work.description));const src=safeUrl(work.src);if(src&&work.type==='image'){const img=el('img');img.src=src;img.alt=work.title;body.append(img);const original=el('a','查看原图','original-link');original.href=src;original.target='_blank';original.rel='noopener noreferrer';body.append(original)}if(src&&work.type==='video'){const video=el('video');video.src=src;video.controls=true;video.playsInline=true;video.preload='metadata';const poster=safeUrl(work.cover);if(poster)video.poster=poster;body.append(video)}if(work.prompt){body.append(el('h3','Prompt'),el('pre',work.prompt));const copy=el('button','复制 Prompt','copy');copy.onclick=async()=>{try{await navigator.clipboard.writeText(work.prompt);copy.textContent='已复制'}catch{copy.textContent='复制失败，请选择上方文本复制'}};body.append(copy)}$('detail').showModal()}
function render(type='all'){$('works').replaceChildren();const works=data.works.filter(w=>type==='all'||w.type===type);$('empty').hidden=works.length>0;$('empty').textContent=type==='all'?'首个作品集正在整理中。':'这个分类的作品还在整理中。';$('works').scrollLeft=0;works.forEach((w,i)=>{const card=el('button',null,'card');card.type='button';card.style.setProperty('--delay',`${Math.min(i,5)*70}ms`);card.setAttribute('aria-label',`查看${w.title}`);const cover=el('div',null,'cover');const src=safeUrl(w.cover||(w.type==='image'?w.src:''));if(src){const img=el('img');img.src=src;img.alt=w.title;img.loading='lazy';img.onerror=()=>cover.replaceChildren(el('span','封面暂不可用'));cover.append(img)}else cover.append(el('span',labels[w.type]||'作品'));card.append(cover,el('h3',w.title),el('div',[labels[w.type],...(w.tags||[])].filter(Boolean).join(' / '),'meta'));card.onclick=()=>show(w,card);if(matchMedia('(hover: hover) and (prefers-reduced-motion: no-preference)').matches){card.addEventListener('pointermove',event=>{const rect=card.getBoundingClientRect();cover.style.setProperty('--rx',`${-(event.clientY-rect.top-rect.height/2)/rect.height*7}deg`);cover.style.setProperty('--ry',`${(event.clientX-rect.left-rect.width/2)/rect.width*9}deg`)});card.addEventListener('pointerleave',()=>{cover.style.setProperty('--rx','0deg');cover.style.setProperty('--ry','0deg')})}$('works').append(card)});requestAnimationFrame(updateGalleryControls)}
document.querySelectorAll('[data-type]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-type]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));render(button.dataset.type)});
document.querySelector('.close').onclick=()=>$('detail').close();$('detail').addEventListener('close',()=>{const video=$('detail').querySelector('video');if(video)video.pause();opener?.focus()});render();

const gallery=$('works');function updateGalleryControls(){$('gallery-prev').disabled=gallery.scrollLeft<=2;$('gallery-next').disabled=gallery.scrollLeft+gallery.clientWidth>=gallery.scrollWidth-2}
function slideGallery(direction){gallery.scrollBy({left:direction*(gallery.querySelector('.card')?.getBoundingClientRect().width+24||gallery.clientWidth),behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'})}
$('gallery-prev').onclick=()=>slideGallery(-1);$('gallery-next').onclick=()=>slideGallery(1);gallery.addEventListener('scroll',updateGalleryControls,{passive:true});window.addEventListener('resize',updateGalleryControls);gallery.addEventListener('keydown',event=>{if(event.target!==gallery)return;if(event.key==='ArrowRight'||event.key==='ArrowLeft'){event.preventDefault();slideGallery(event.key==='ArrowRight'?1:-1)}});updateGalleryControls();
